<?php

namespace App\Traits;

use App\Models\Location;
use Ramsey\Uuid\Uuid;

trait CreatingLocationWithIdUuid
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $location = Location::get();
        $user = auth()->user();
        if (count($location) <= 1) {
            self::creating(function ($model) {
                $model->id = Uuid::uuid4()->toString();
                $model->location_id = Location::first()?->id;
            });
        } else {
            self::creating(function ($model) use ($user, $location) {
                $model->id = Uuid::uuid4()->toString();
                if ($user) {
                    if ($user->role_id == config('constants.role.adminId')) {
                        $model->location_id = session()->get('localization_for_changes_data')['id'] ?? $location->first()->id;
                    } else {
                        $model->location_id = $user->location_id;
                    }
                }
            });
        }
    }
}
